// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnfuwjrfaeiodexezedh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZnV3anJmYWVpb2RleGV6ZWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODgyNjUsImV4cCI6MjA2NzY2NDI2NX0.fPhps5QOy_0wXsZqLzpVviHizUalFpBiHrHZztx_pqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});